### ISSUE TITLE
installation and run

### ISSUE THREAD

**Issue by xsiriusx** [vitaliy-sk/keenetic-grafana-monitoring#10]
when docker run image
`
Traceback (most recent call last):
  File "/home/keentic_influxdb_exporter.py", line 110, in <module>
    infuxdb_writer = InfuxWriter(config['influx2'], config_path)
  File "/usr/local/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'influx2'
`
And crash

**Comment by vitaliy-sk** [comment]
@xsiriusx please share your config file

**Comment by xsiriusx** [comment]
[influx2]
url=http://localhost:8086 
# For influx v1.x please use "-" as a value
org=keenetic
# For influx v1.x please use "username:password" as a token
token=mytoken
timeout=6000
# For influx v1.x DB name
bucket=keenetic
[keenetic]
admin_endpoint=http://ipkeenetic:80
skip_auth=false
login=myuser
password=mypass
[collector]
interval_sec=30

**Comment by xsiriusx** [comment]
this is command for buil docker

```
git clone you repository

edit config.ini

docker build image

docker run image
```

maybe something wrong?

**Comment by vitaliy-sk** [comment]
@xsiriusx You don't need to pull the repo and build image.
Please follow steps from README.md step by step.
