### ISSUE TITLE
NAT sessions is empty on the Grafana dashboard

### ISSUE THREAD

**Issue by FlyingHavoc** [vitaliy-sk/keenetic-grafana-monitoring#11]
When, I'm checking "NAT Sessions" graph in Grafana - it is empty.

Correct me if I'm wrong, but it seems that "ip nat" command is missing in metrics.json?
Or is this another reason why "ip nat" is not collected?

Update:
I've checked and "ip nat" metrics collection seems to be gone starting from metrics.json in 1.1.1 release.

In 1.1.0 release metrics.json:
`  {`
`      "command": "ip nat",`
`      "root" : "$.[*]",`
`      "tags" : {`
`        "src" : "$.src",`
`        "dst" : "$.dst"`
`      },`
`      "values" : {`
`        "bytes-in": "$.bytes",`
`        "bytes-out": "$.bytes-out"`
`      }`
`    }, `

**Comment by vitaliy-sk** [comment]
@FlyingHavoc yes, it was removed due to performance reason on InfluxDB side. 
If you want to collect NAT session you can override metrics.json, see example in [readme](https://github.com/vitaliy-sk/keenetic-grafana-monitoring#run-in-docker-on-seprate-host-recommended) 
please note that it generate a lot of data in influx, so you need to be sure that your influx host is ready to handle this

**Comment by FlyingHavoc** [comment]
> @FlyingHavoc yes, it was removed due to performance reason on InfluxDB side.
> If you want to collect NAT session you can override metrics.json, see example in [readme](https://github.com/vitaliy-sk/keenetic-grafana-monitoring#run-in-docker-on-seprate-host-recommended)
> please note that it generate a lot of data in influx, so you need to be sure that your influx host is ready to handle this

@vitaliy-sk Thanks for the message.

I'm still on influxdb 1.8 version.
I have created retention policy for keenetic database now.

> SHOW RETENTION POLICIES ON "keenetic"
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        true

> CREATE RETENTION POLICY "two_months" ON "keenetic" DURATION 60d REPLICATION 1 DEFAULT

> SHOW RETENTION POLICIES ON "keenetic"
name       duration  shardGroupDuration replicaN default
----       --------  ------------------ -------- -------
autogen    0s        168h0m0s           1        false
two_months 1440h0m0s 24h0m0s            1        true
>
