### ISSUE TITLE
Dashboard for InfluxDB2 (Flux panels)

### ISSUE THREAD

**Issue by andrico21** [vitaliy-sk/keenetic-grafana-monitoring#12]
Do you have Grafana dashboard with new panels?
I've checked https://grafana.com/grafana/dashboards/12723 but there's only InfluxQL version of panels - not working with InfluxDB2 database.

p.s. fresh deploy of collector and fresh InfluxDB2 installation, data is collecting fine, but no visualization.

**Comment by vitaliy-sk** [comment]
@andrico21 it should be compatible with old dashboard 
you need to select Query Language: InfluxQL while adding data source in Grafana

![SCR-20220219-r8x](https://user-images.githubusercontent.com/2773025/154812384-2a380756-62ec-4eee-8020-e4f42544139d.png)

**Comment by andrico21** [comment]
> @andrico21 it should be compatible with old dashboard you need to select Query Language: InfluxQL while adding data source in Grafana
hmmm, tried this way, but no luck: bucket keenetic exists in the DB with proper read token
![image](https://user-images.githubusercontent.com/44984087/154813397-7c899f78-0a43-4e3c-844c-261642ed50d8.png)

**Comment by vitaliy-sk** [comment]
Please ensure that header has the following format 
Authorization: **Token** <TOKEN_VALUE>

**Comment by vitaliy-sk** [comment]
@andrico21 did you manage the issue?
if you created update dashboard, feel free to share

**Comment by andrico21** [comment]
> @andrico21 did you manage the issue? if you created update dashboard, feel free to share

Hi, actually no - just using old one
