### ISSUE TITLE
How can I add temperature data on Keenetic to grafana.

### ISSUE THREAD

**Issue by g-sezen** [vitaliy-sk/keenetic-grafana-monitoring#16]
Hi,
How can I add temperature data on keenetic to grafana.

![keenetic-temperature](https://github.com/vitaliy-sk/keenetic-grafana-monitoring/assets/105906123/e022682e-429f-477e-91d9-24c44443bafa)

**Comment by g-sezen** [comment]
metrics.json

{
      "command": "interface",
      "root": "$",
      "param" : {
        "name" : "WifiMaster0"
      },
      "tags": {},
      "values" : {
        "temperature": "$.temperature"
      }
    },

After adding this code I was able to run it.

**Comment by vitaliy-sk** [comment]
Added in [2.0.2](https://github.com/vitaliy-sk/keenetic-grafana-monitoring/releases/tag/2.0.2)
