### ISSUE TITLE
Excessive logging in Keenetic syslog with monitoring enabled

### ISSUE THREAD

**Issue by FlyingHavoc** [vitaliy-sk/keenetic-grafana-monitoring#4]
Hello,

Is there a way to avoid or disable Excessive logging in Keenetic syslog when monitoring is enabled?

These messages are repeated every collection interval (interval_sec=30)
(using collector with docker image latest=1.1.1)

------------------------
Oct 20 11:25:47 ndm
Json::Object: AppendMember: duplicate key: "bioset".
Oct 20 11:25:47 ndm
Core::Syslog: last message repeated 14 times.
Oct 20 11:25:47 ndm
Json::Object: AppendMember: duplicate key: "RtmpCmdQTask".
Oct 20 11:25:47 ndm
Json::Object: AppendMember: duplicate key: "RtmpWscTask".
Oct 20 11:25:47 ndm
Json::Object: AppendMember: duplicate key: "HwCtrlTask".
Oct 20 11:25:47 ndm
Json::Object: AppendMember: duplicate key: "ser_task".
Oct 20 11:25:47 ndm
Json::Object: AppendMember: duplicate key: "RtmpMlmeTask".
Oct 20 11:25:47 ndm
Json::Object: AppendMember: duplicate key: "nginx: worker process".
Oct 20 11:25:47 ndm
Core::Syslog: last message repeated 2 times.

**Comment by avorotyagin** [comment]
really appreciate your help if we can fix this
