### ISSUE TITLE
Should not require InfluxDB admin privileges for existing DB pre-created before

### ISSUE THREAD

**Issue by andrico21** [vitaliy-sk/keenetic-grafana-monitoring#6]
Have existing common InfluxDB 1.8 instance already used for different metrics. 
So it's nice to just create new DB once with only write access for particular InfluxDB user. But application tries to recreate DB every time a container deploys. Is there any way to avoid DB recreation attempts? just not found any existing config.ini parameters to change its behaviour

influxdb.exceptions.InfluxDBClientError: 403: {"error":"error authorizing query: keeneticmonwriter not authorized to execute statement 'CREATE DATABASE keeneticmetrics', requires admin privilege"}

**Comment by vitaliy-sk** [comment]
@andrico21 application try to create DB only if it abesnt. 
please check that your DB exists and the user can see it `SHOW DATABASES`

**Comment by a1ekseev** [comment]
> @andrico21 application try to create DB only if it abesnt. please check that your DB exists and the user can see it `SHOW DATABASES`

I will! As soon as I understand how to work queries through Flux.

**Comment by vitaliy-sk** [comment]
Closed due unactivity
